# -*- coding: utf-8 -*-
"""ch03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vn5AkCoeSijBcF_5QO5oWTra0AG9SBf-

3일차
"""

pac = ["hello","world","good","bye"] # 패킹
str_1, str_2, str_3, str_4 = pac #언패킹

list_1=[1,2,3,4,5]

keys = ["one","two","three"]
values = (1,2,3)

dict_5=dict(zip(keys, values))

list(dict_5.keys())

dict_5.values()

dict_5.items()

s1=set([1,2,3,4,5])
s2=set([4,5,6,7,8,9])

s1&s2

s1|s2

list_1=[1,2,3,4]

tuple_1=(1,2,3,4)

dic_1={'1':'my','2':'name','3':'is','4':'병길'}

dic_1[5]='이다'

dic_1['1']

type(dic_1.keys())

dic_1.get('4')

dic_1.get('6','x')

'1' in dic_1

5 in dic_1

"""# 집합의 종류
- set : 변경 가능한 집합
- frozenset : 변경 불가능한 집합
"""

set_a = ((1,2,3,4,5,6))

type(set_a)

set_a

"""모든테이터가 집합의 원소가 될 수는 없다.
hashable + 변경불가능한 자료형만 집합의 원소로 사용될 수 있다.

# 제어문
"""

score = 81
if score >= 80:
  print("합격입니다.")
else:
    print("불합격입니다.")

"""- 4줄 또는 2줄 들여쓰기
```python
if<condition>:
  <수행할 문장1>
  <수행할 문장2>
else:
  <수행할 문장3>

```

다음과 같이 출력되는 code 작성
점수를 입력하세요 : xx
xx 점으로 합격입니다.
xx 점으로 불합격입니다.
"""

score = float(input("점수를 입력하세요 : "))
if score >= 60 :
  print(" %d 점으로 합격입니다." %score)
else :
  print(" %d 점으로 불합격입니다." %score)

score = int(input("점수를 입력하세요 : "))
condition = score >= 60
if condition :
  print(f"{score} 점으로 합격입니다.")
else :
  print(f"{score} 점으로 불합격입니다.")

score_m = int(input("수학 점수를 입력하세요 : "))
score_e = int(input("영어 점수를 입력하세요 : "))
condition = (score_m >= 80) & (score_e >= 80)
if condition :
  print(f" 수학 {score_m}점, 영어 {score_e} 점으로 합격입니다.")
else :
  print(f"수학 {score_m}점, 영어 {score_e} 점으로 불합격입니다.")

"""# 연습문제"""

srp = input("가위, 바위, 보! : ")
if srp =="가위":
  print("이겼다!")
elif srp == "바위":
  print("졌다...")
elif srp == "보":
  print("비겼다.")
else :
  print("가위, 바위, 보 중에 하나만 선택하세요!")

year = int(input("태어난 연도를 입력해주세요 : "))
age = 2022-year
age_g = (age//10)*10
print(f"나의 나이는 {age}이고 {age_g}대 입니다.")

year = int(input("태어난 연도를 입력해주세요 : "))
age = 2022-year
if (age >=10) & (age< 20) :
  age_g = 10
elif (age >= 20) & (age < 30) :
  age_g = 20
elif (age >= 30) & (age < 40) :
  age_g = 30
else :
  age_g = "잘 모르겠네요;;" 
print(f"나의 나이는 {age}살이고 {age_g}대 입니다.")

score = input("점수를 입력해주세요(정수만) : ")
if score.isdigit() == True :
  score = int(score)
  if (score >=90) & (score <= 100) :
    grade = "A" 
    rate = "참 잘했어요!"
  elif (score >= 80) & (score <90) :
    grade = "B" 
    rate = "더 잘 할 수 있을거에요!"
  elif (score >= 70) & (score <80) :
    grade = "C"
    rate = "좀 더 노력해봐요!"
  elif (score >= 60) & (score <70) :
    grade = "D"
    rate = "노력해야겠어요."
  elif (score >= 0) & (score <60) :
    grade = "F"
    rate = "......"
  else :
    grade = "없음"
    rate = "?"

    print(f"당신의 점수는 {score}입니다.")
    if (score < 0) or (score > 100) :
      print("올바른 점수를 입력하세요.")
    else :
      print(f"당신의 등급 : {grade} \n{rate} ")
else :
  print("잘못 입력했습니다.")

score = input("점수를 입력해주세요 : ")
if score.isdigit() == True :
  score = int(score)
  if (score >=90) & (score <= 100) :
    print("당신의 등급 : A ")
  elif (score >= 80) & (score <90) :
    print("당신의 등급 : B ")
  elif (score >= 70) & (score <80) :
    print("당신의 등급 : C ")
  elif (score >= 60) & (score <70) :
    print("당신의 등급 : D ")
  elif (score >= 0) & (score <60) :
    print("당신의 등급 : F ")
  else :
    print("올바른 점수를 입력하세요.")
else :
  print("잘못 입력했습니다.")

"""#추가연습문제 (데이터 사이언스 스쿨)"""

a=4
if a % 2 ==0:
  print("짝수")
else:
  print("홀수")

b = 14
if (b >= 10) & ( b < 100) & (b % 2 == 0):
  print("2자리의 짝수이다.")
else :
  print("2자리 수의 짝수가 아니다.")

year = int(input("연도를 입력해주세요 : "))
if (year % 4) == 0 :
  if ((year % 100) == 0) & ((year % 400) != 0) :
    print("평년입니다.")
  else:
    print("윤년입니다.")
else :
  print("윤년이 아닙니다.")

c = 9
if c >= 8:
  print("A")
elif c >= 5:
  print("B")
else:
  print("C")

watermelon = int(input("수박의 무게는? : "))
if watermelon >= 10 :
  print("1등급입니다.")
elif watermelon >= 7 :
  print("2등급입니다.")
elif watermelon >= 4 :
  print("3등급입니다.")
else :
  print("4등급입니다.")

sex = "boy"
pushup = 8
if sex == "boy":
  if pushup >=10:
    grade = "Pass"
  else:
    grade = "Fail"
else:
  if pushup >= 10:
    grade = "Pass"
  else:
    grade = "Fail"
print(grade)

